name: deploy NodeJS Email Sender

on: push

# Environment variables available to all jobs and steps in this workflow
env:
  IBM_CLOUD_REGION: eu-gb
  IBM_CLOUD_GROUP: default
  IBM_CLOUD_SPACE: ${{secrets.IBM_CLOUD_SPACE}}
  IBM_CLOUD_ORG: iamadeniyiismail@gmail.com
  MANIFEST_NAME: manifest.yaml
  IBM_CLOUD_API: ${{secrets.IBM_CLOUD_API_KEY}}

defaults:
  run:
    working-directory: .

jobs:
  Deploy-app:
    name: Deploy NodeJS Email Sender App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install IBM CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
        shell: bash
      - name: Install npm dependencies
        run: | 
          npm ci --production
        shell: bash
      - name: Install CF plugin
        run: ibmcloud cf install -f
        shell: bash
      - name: Log into IBM Cloud
        run: |
          ibmcloud login --apikey "$IBM_CLOUD_API" -r "$IBM_CLOUD_REGION"
        shell: bash
      - name: Target CF
        run: ibmcloud target --cf-api https://api.$IBM_CLOUD_REGION.cf.cloud.ibm.com -r $IBM_CLOUD_REGION -o $IBM_CLOUD_ORG -s $IBM_CLOUD_SPACE
        shell: bash
      - name: Deploy manifest file
        run: ibmcloud cf push -f $MANIFEST_NAME
        shell: bash
